server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: jedi-service
              uri: lb://jedis
              predicates:
                - Path=/api/v1/jedis/**

            - id: sables-service
              uri: lb://sables
              predicates:
                - Path=/api/v1/sables/**