server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns: "*"
                allowed-methods: "*"
                allowed-headers: "*"
                exposed-headers: "*"
                allow-credentials: false
                max-age: 3600

          routes:
            - id: jedi-service
              uri: lb://jedis
              predicates:
                - Path=/api/v1/jedis/**, /api/v2/jedis/**, /jedis/api-docs/**

            - id: cristales-service
              uri: lb://sables
              predicates:
                - Path=/api/v1/cristales/**, /api/v2/cristales/**, /cristales/api-docs/**

            - id: sables-service
              uri: lb://sables
              predicates:
                - Path=/api/v1/sables/**, /api/v2/sables/**, /sables/api-docs/**

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: Microservicio Jedis
        url: /jedis/api-docs
      - name: Microservicio Sables
        url: /sables/api-docs
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false